import cv2
import numpy as np
img = cv2.imread('imgs/tiger.jpg',flags=0)
img_blur=cv2.GaussianBlur(src=img,ksize=(5,5),sigmaX=0,sigmaY=0)
cv2.imshow('Tiger Image',img)
cv2.waitKey()
cv2.imshow('Tiger Image Blurred',img_blur)
cv2.waitKey()
cv2.destroyAllWindows()
sobelx = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=1, dy=0, ksize=5)
sobely = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=0, dy=1, ksize=5) 
sobelxy = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=1, dy=1, ksize=5) 
cv2.imshow('Sobel X', sobelx)
cv2.waitKey(0)
cv2.imshow('Sobel Y', sobely)
cv2.waitKey(0)
cv2.imshow('Sobel X Y using Sobel() function', sobelxy)
cv2.waitKey(0)
can = cv2.Canny(img_blur,threshold1=100,threshold2=200)
cv2.imshow('Canny Edges Detection',can)
cv2.waitKey()
cv2.destroyAllWindows()